parameters:
  werkint_voter.poller.class:
    Werkint\Bundle\VoterBundle\Service\Poller
  werkint_voter.voterstorage.class:
    Werkint\Bundle\VoterBundle\Service\VoterStorage

services:
  werkint_voter.poller:
    class: %werkint_voter.poller.class%
    arguments:
      - @werkint_voter.voterstorage

  werkint_voter.voterstorage:
    class: %werkint_voter.voterstorage.class%
